services:
  nginx:
    container_name: nginx
    image: nginx
    build: requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    restart: always
    secrets:
      - db_password
      - admin_password
      - user_password
      - redis_password

  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always
    secrets:
      - db_root_password
      - db_password

  redis:
    container_name: redis
    image: redis
    build: requirements/bonus/redis
    networks:
      - inception
    restart: always
    secrets:
      - redis_password

  ftp:
    container_name: ftp
    image: ftp
    build: requirements/bonus/ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always
    secrets:
      - ftp_password

  adminer:
    container_name: adminer
    image: adminer
    build: requirements/bonus/adminer
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always

  static:
    container_name: static
    image: static
    build: requirements/bonus/static
    ports:
      - "8081:8081"
    networks:
      - inception
    restart: always

  portainer:
    container_name: portainer
    image: portainer
    build: requirements/bonus/portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  portainer_data:
    driver: local

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  admin_password:
    file: ../secrets/admin_password.txt
  user_password:
    file: ../secrets/user_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
  redis_password:
    file: ../secrets/redis_password.txt