services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    restart: always

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

  redis:
    build: requirements/bonus/redis
    container_name: redis
    networks:
      - inception
    restart: always

  ftp:
    build: requirements/bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always

  static:
    build: requirements/bonus/static
    container_name: static
    ports:
      - "8081:8081"
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wel-kass/data/mariadb
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/wel-kass/data/wordpress

networks:
  inception:
    driver: bridge
